ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$HOME/dotfiles/custom"
ZSH_THEME="nathan"

DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"

setopt auto_cd
setopt auto_pushd
setopt prompt_subst

source $ZSH/oh-my-zsh.sh

# Load other files
for file in ~/dotfiles/bash/*; do
  . "$file"
done
