ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$HOME/dotfiles/custom"
ZSH_THEME="nathan"

DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"

setopt auto_cd
setopt auto_pushd
setopt prompt_subst

source $ZSH/oh-my-zsh.sh

# Load other files
for file in ~/dotfiles/bash/*; do
  . "$file"
done

if [ -d ~/.nvm ]; then
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi
